[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://advancechatappbackend.onrender.com/api"
  VITE_SOCKET_URL = "https://advancechatappbackend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 